# Generated by Django 5.0.6 on 2024-05-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
