# Generated by Django 5.0.6 on 2024-05-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_license_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
