# Generated by Django 5.0.6 on 2024-05-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_license_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
