# Generated by Django 5.0.6 on 2024-05-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_alter_license_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='application_type',
            field=models.CharField(blank=True, choices=[('Private Mobile Network', 'Private Mobile Network'), ('Coverage Licensing', 'Coverage Licensing'), ('Private Telecoms Network', 'Private Telecoms Network'), ('Equipment Approval', 'Equipment Approval'), ('Frequency Spectrum Allocation', 'Frequency Spectrum Allocation')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default='active', max_length=10),
        ),
    ]
