# Generated by Django 5.0.6 on 2024-05-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0007_licenseapplication_coveragelicenseapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='application_type',
            field=models.CharField(blank=True, choices=[('private_mobile_network', 'Private Mobile Network'), ('coverage_licensing', 'Coverage Licensing'), ('private_telecoms_network', 'Private Telecoms Network'), ('equipment_approval', 'Equipment Approval'), ('frequency_spectrum_allocation', 'Frequency Spectrum Allocation')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default='Active', max_length=10),
        ),
    ]
