# Generated by Django 5.0.6 on 2024-05-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0008_alter_license_application_type_alter_license_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseapplication',
            name='user',
        ),
    ]
